K,{template:{configurable:!0,enumerable:!0,get:function(){if(void 0===IKb){var a=document.createElement("template");J(a,"<!--css-build:shady--><tp-yt-paper-item active=\"[[active]]\" on-click=\"onClick\" class=\"style-scope yt-live-chat-text-input-field-suggestion\">\n  <img alt=\"[[data.alt]]\" hidden$=\"[[!identity(data.image)]]\" src$=\"[[data.image.thumbnails.0.url]]\" author$=\"[[data.author]]\" class=\"style-scope yt-live-chat-text-input-field-suggestion\">\n  [[data.text]]\n</tp-yt-paper-item>\n");
a.content.insertBefore(M().content.cloneNode(!0),a.content.firstChild);var b=a.content,c=b.insertBefore;if(void 0===HKb){var d=document.createElement("template");J(d,"");
HKb=d}d=HKb;c.call(b,d.content.cloneNode(!0),a.content.firstChild);IKb=a}a=IKb;return a}}});
var kK=jK;kK.prototype.dataChanged=kK.prototype.dataChanged;x([U(),A("design:type",Object)],kK.prototype,"data",void 0);x([U({reflectToAttribute:!0}),A("design:type",Boolean)],kK.prototype,"active",void 0);x([T("data"),A("design:type",Function),A("design:paramtypes",[]),A("design:returntype")],kK.prototype,"dataChanged",null);kK=x([$w({is:"yt-live-chat-text-input-field-suggestion",noInjection:!0})],kK);var JKb=function(){var a=H.apply(this,arguments)||this;a.viewerName=null;a.actionMap={"yt-live-chat-actions":"onChatMessage_"};a.SUPPORTED_ITEM_TYPES_=["liveChatTextMessageRenderer","liveChatLegacyPaidMessageRenderer","liveChatPaidMessageRenderer"];a.PARTICIPANT_TIME_USEC_=3E8;return a};
m(JKb,H);e=JKb.prototype;e.created=function(){this.allParticipantsCharMap_={};this.JSC$13647_asyncHandle_=null};
e.addParticipant=function(a){var b=Uaa(this.participants,a,function(d,f){d=d[Object.keys(d)[0]];f=f[Object.keys(f)[0]];d=String(Mu(d.authorName)).toLowerCase();f=String(Mu(f.authorName)).toLowerCase();return d<f?-1:d==f?0:1}.bind(this));
if(0<=b){var c=this.participants[b];c[Object.keys(c)[0]].timestampUsec&&this.splice("participants",b,1,a)}else this.splice("participants",-b-1,0,a);a=a[Object.keys(a)[0]];b=Mu(a.authorName).toLocaleLowerCase();c=b.substr(0,2);this.allParticipantsCharMap_.hasOwnProperty(c)||(this.allParticipantsCharMap_[c]={});this.allParticipantsCharMap_[c][b]=a};
e.getAuthorsFromPrefix=function(a){return this.allParticipantsCharMap_.hasOwnProperty(a)?this.allParticipantsCharMap_[a]:null};
e.computeViewerRegex_=function(a){if(!a)return null;a=a.replace(/[-\/\\^$*+?.()|[\]{}]/g,"\\$&");return new RegExp("([@#]?"+a.replace(/ /g,"\\s*")+")","ig")};
e.checkForStaleParticipants_=function(){this.trimOldParticipants_();this.JSC$13647_asyncHandle_&&this.cancelAsync(this.JSC$13647_asyncHandle_);0<this.participants.length&&(this.JSC$13647_asyncHandle_=this.async(this.checkForStaleParticipants_,3E4))};
e.onChatMessage_=function(a){var b=this,c=1E3*Date.now();a.forEach(function(d){if(d=C(d,UH)){d=d.item;var f=Object.keys(d)[0];-1!=b.SUPPORTED_ITEM_TYPES_.indexOf(f)&&d[f].timestampUsec>=c-b.PARTICIPANT_TIME_USEC_&&b.addParticipant(d)}},this);
this.checkForStaleParticipants_()};
e.trimOldParticipants_=function(){for(var a=1E3*Date.now(),b=this.participants.length-1;0<=b;b--){var c=this.participants[b];c=c[Object.keys(c)[0]];c.timestampUsec&&c.timestampUsec<a-this.PARTICIPANT_TIME_USEC_&&this.splice("participants",b,1)}};
var lK=JKb;x([O(Lw.YtActionHandlerBehavior),A("design:type",Object)],lK.prototype,"ytActionHandlerBehavior",void 0);x([U(),A("design:type",Object)],lK.prototype,"viewerName",void 0);x([U({computed:"computeViewerRegex_(viewerName)"}),A("design:type",Object)],lK.prototype,"viewerRegex",void 0);x([U({value:function(){return[]},
notify:!0}),A("design:type",Array)],lK.prototype,"participants",void 0);lK=x([$w({is:"yt-live-chat-participants-manager",noInjection:!0})],lK);var KKb=/.*([:@#].*?)$/,LKb=/\u00a0/g,MKb=String.fromCharCode(160),NKb={placeholderTextColor:"--yt-live-chat-text-input-field-placeholder-color",activeUnderlineColor:"--yt-live-chat-text-input-field-active-underline-color",inactiveUnderlineColor:"--yt-live-chat-text-input-field-inactive-underline-color"},mK=function(){var a=H.apply(this,arguments)||this;a.disabled=!1;a.liveChatRichMessageInput=null;a.messageInput=null;a.isValidWithNoInputText=!1;a.suggestions=[];a.emojiManager=gK;a.suggestionIndex=
-1;a.JSC$13652_lastSuggestionRange=null;return a};
m(mK,H);e=mK.prototype;e.configureRendererStamper=function(){return{suggestions:{id:"dropdown-content",mapping:{suggestion:"yt-live-chat-text-input-field-suggestion"},reuseComponents:!0}}};
e.ready=function(){this.scopeSubtree(this.$.input,!0)};
e.attached=function(){yd&&(document.execCommand("enableObjectResizing",!1,"false"),document.execCommand("enableInlineTableEditing",!1,"false"))};
e.detached=function(){this.setLiveChatRichMessageInput(null)};
e.dataChanged=function(a){var b=!1,c={},d;for(d in NKb)a&&a.hasOwnProperty(d)&&(c[NKb[d]]=this.colorFromDecimal(a[d]),b=!0);b&&this.updateStyles(c);this.messageInput&&this.setLiveChatRichMessageInput(this.messageInput)};
e.onMessageSet=function(a){this.setLiveChatRichMessageInput(a||{})};
e.colorFromDecimal=function(a){a=Math.floor(Number(a));return"rgba("+[a>>16&255,a>>8&255,a&255,(a>>24&255)/255].join()+")"};
e.preventDrag=function(a){a.dataTransfer&&(a.dataTransfer.dropEffect="none");a.preventDefault()};
e.preventResize=function(a){a.returnValue=!1};
e.onInputChange=function(){var a=this.getCurrentRange();if(a){var b=this.calculateTextBeforeRange(a);this.completeEmojisInRange(a,b,!0)||this.updateSuggestions(a,b)}a=this.calculateLiveChatRichMessageInput();this._setLiveChatRichMessageInput(a);this.fire("yt-live-chat-message-input-change",a)};
e.getCurrentRange=function(){var a=window.getSelection();return a&&a.rangeCount?a.getRangeAt(0).cloneRange():null};
e.getInputRange=function(){var a=this.getCurrentRange();if(a){for(var b=a.commonAncestorContainer,c=!1;b;){if(b===this.$.input){c=!0;break}b=b.parentNode}c||(a=null)}a||(a=this.getRangeAtEnd());return a};
e.getRangeAtEnd=function(){var a=document.createRange();this.$.input.lastChild?a.setStart(this.$.input.lastChild,this.$.input.lastChild.childNodes.length):(a.selectNodeContents(this.$.input),a.collapse(!1));return a};
e.getSuggestions=function(a){var b=[],c=a.substring(0,3),d=this.getEmojiManager(),f=CKb(d,c);if(f)for(var h in f)if(0===h.toLocaleLowerCase().indexOf(a)){var l=f[h];if(l&&l.emojiId){if(l=BKb(d,l.emojiId)){var n=void 0,p=void 0,t=void 0,y=void 0,E=(null==(n=l.image)?0:null==(p=n.accessibility)?0:null==(t=p.accessibilityData)?0:t.label)||l.isCustomEmoji?null==(y=l.shortcuts)?void 0:y[0]:l.emojiId;b.push({suggestion:{emoji:!0,image:l.image,alt:E,text:h,textToInsertWhenSelected:l.isCustomEmoji?h:E}})}if(64<=
b.length)break}}if(!this.participantsManager)return null;if(0===c.indexOf("@")||0===c.indexOf("#"))if(d=c.substring(0,1),a=a.substring(1),c=c.substring(1),c=this.participantsManager.getAuthorsFromPrefix(c))for(var F in c)if(0===F.indexOf(a)&&(f=c[F],h=Mu(f.authorName),b.push({suggestion:{author:!0,authorType:d,image:f.authorPhoto,alt:h,text:h}}),64<=b.length))break;return b?b.sort(function(I,L){return L.suggestion.text<I.suggestion.text?-1:L.suggestion.text===I.suggestion.text?0:1}):null};
e.insertSuggestion=function(a){a.emoji?this.insertTextAtRange(this.JSC$13652_lastSuggestionRange,a.textToInsertWhenSelected||""):a.author&&this.insertTextAtRange(this.JSC$13652_lastSuggestionRange,a.authorType+a.text+MKb)};
e.updateSuggestionsAtCaret=function(){var a=this.getCurrentRange();a&&this.updateSuggestions(a,this.calculateTextBeforeRange(a))};
e.offsetStartOfRangeBy=function(a,b){for(;0<b;)if(0<=a.startOffset-b){a.setStart(a.startContainer,a.startOffset-b);break}else{b=a.startContainer instanceof HTMLImageElement?b-a.startContainer.alt.length:b-a.startOffset;var c=a.startContainer.previousSibling;if(!c){a.setStart(a.startContainer,0);break}a.setStart(c,c.childNodes.length||0)}};
e.updateSuggestions=function(a,b){var c=this;this.JSC$13652_lastSuggestionRange&&(this.JSC$13652_lastSuggestionRange.detach(),this.JSC$13652_lastSuggestionRange=null);if((b=KKb.exec(b))&&b.length&&(b=b[b.length-1].toLocaleLowerCase(),2<b.length&&(this.offsetStartOfRangeBy(a,b.length),this.JSC$13652_lastSuggestionRange=a,(a=this.getSuggestions(b))&&a.length))){this.suggestions=a;zp(this,function(){c.$["dropdown-content"].scrollTop=Math.pow(2,24)});
this.dropdown.opened?this.dropdown.notifyResize():this.dropdown.opened=!0;this.suggestionIndex=-1;this.changeSuggestionIndex(a.length-1);return}this.dropdown.opened=!1};
e.completeEmojisInRange=function(a,b,c){var d=b.replace(/[\s\xa0]+$/,"");b=b.length-d.length;d=d.split(" ");d=d[d.length-1].trim().toLocaleLowerCase();var f=d.lastIndexOf(":");if(c&&!b&&f!==d.length-1)return!1;-1!==f&&(c=d.lastIndexOf(":",f-1),-1!==c&&(d=d.substring(c)));f=this.getEmojiManager();if((c=fK(f,d))&&c.emojiId){c=BKb(f,c.emojiId)||null;this.offsetStartOfRangeBy(a,d.length+b);var h,l,n,p;d=((null==(h=c)?0:h.isCustomEmoji)?null==(l=c)?void 0:null==(n=l.shortcuts)?void 0:n[0]:null==(p=c)?
void 0:p.emojiId)||"";b&&(d+=MKb);this.insertTextAtRange(a,d);this.dropdown.opened=!1;return!0}return!1};
e.onSuggestion=function(a){this.insertSuggestion(a.detail);this.dropdown.opened=!1};
e.onKeyPress=function(a){13===a.keyCode&&(a.preventDefault(),this.dropdown.opened?(this.insertSuggestion(this.suggestions[this.suggestionIndex].suggestion),this.dropdown.opened=!1):this.fire("yt-live-chat-send-message"))};
e.completeEmojis=function(){var a=document.createRange();this.$.input.lastChild?a.setStart(this.$.input.lastChild,this.$.input.lastChild.childNodes.length):(a.selectNodeContents(this.$.input),a.collapse(!1));this.completeEmojisInRange(a,this.calculateTextBeforeRange(a),B("live_chat_require_space_for_autocomplete_emoji"))};
e.maybePreventTextFormatting=function(a){!Id||!a.ctrlKey&&!a.metaKey||66!==a.keyCode&&73!==a.keyCode||(a.stopImmediatePropagation(),a.preventDefault())};
e.onKeyDown=function(a){this.maybePreventTextFormatting(a);if(this.dropdown.opened)switch(a.keyCode){case 27:this.dropdown.opened=!1;a.stopPropagation();break;case 9:this.insertSuggestion(this.suggestions[this.suggestionIndex].suggestion);this.dropdown.opened=!1;a.preventDefault();break;case 38:this.changeSuggestionIndex(this.suggestionIndex-1);a.preventDefault();break;case 40:this.changeSuggestionIndex(this.suggestionIndex+1),a.preventDefault();}};
e.onKeyUp=function(a){switch(a.keyCode){case 37:case 39:this.updateSuggestionsAtCaret();break;case 38:case 40:this.dropdown.opened||this.updateSuggestionsAtCaret();}if(vd)this.onInputChange()};
e.changeSuggestionIndex=function(a){if(this.dropdown.opened){var b=this.$["dropdown-content"];0<=this.suggestionIndex&&this.suggestionIndex<b.children.length&&(b.children[this.suggestionIndex].active=!1);var c=this.suggestions.length;this.suggestionIndex=(a+c)%c;a=b.children[this.suggestionIndex];a.active=!0;b.scrollTop=a.offsetTop}};
e.onInputPaste=function(a){a.preventDefault();(a=a.clipboardData)&&a.types&&(a=a.getData("text/plain")||"",a=a.replace(/\n/g,""),this.insertText(a))};
e.onFocus=function(){this._setFocused(!0)};
e.onBlur=function(){this._setFocused(!1)};
e.insertText=function(a){this.insertTextAtRange(this.getInputRange(),a)};
e.insertTextAtRange=function(a,b){if(a){a.collapsed||a.deleteContents();var c=this.getEmojiManager();if(c){b=c.createDocumentFragment(b,!0,!1);if(!b)return;c=k((null==b?void 0:b.childNodes)||[]);for(var d=c.next();!d.done;d=c.next()){d=d.val