te>\n</div>\n");a.content.insertBefore(M().content.cloneNode(!0),
a.content.firstChild);var b=a.content,c=b.insertBefore;if(void 0===w8b){var d=document.createElement("template");J(d,"");
w8b=d}d=w8b;c.call(b,d.content.cloneNode(!0),a.content.firstChild);x8b=a}a=x8b;return a}}});
var z8b=y8b;x([U(),A("design:type",Object)],z8b.prototype,"data",void 0);z8b=x([V({is:"ytd-handles-claiming-faq-section-renderer"})],z8b);var A8b;var B8b;var C8b=function(){var a=H.apply(this,arguments)||this;a.rightSquigglyDark="https://www.gstatic.com/youtube/img/handles/handles_squiggle_1_dark_v1.svg";a.rightSquigglyLight="https://www.gstatic.com/youtube/img/handles/handles_squiggle_1_light_v1.svg";a.leftSquigglyDark="https://www.gstatic.com/youtube/img/handles/handles_squiggle_2_dark_v1.svg";a.leftSquigglyLight="https://www.gstatic.com/youtube/img/handles/handles_squiggle_2_light_v1.svg";a.leftSquiggly=a.leftSquigglyLight;a.rightSquiggly=a.rightSquigglyLight;
a.actionMap={"yt-dark-mode-toggled-action":"onDarkModeToggledAction"};a.actionButtonOverride={style:"mono",type:"filled",size:"XL"};a.darkerDarkTheme=B("web_darker_dark_theme");return a};
m(C8b,H);e=C8b.prototype;e.updateLeftSquigglyStyle=function(){this.updateStyles({"--yt-left-squiggly-background":"url("+this.leftSquiggly+")"})};
e.updateRightSquigglyStyle=function(){this.updateStyles({"--yt-right-squiggly-background":"url("+this.rightSquiggly+")"})};
e.ready=function(){var a=document.documentElement.hasAttribute("dark");this.onDarkModeToggledAction(a)};
e.onDarkModeToggledAction=function(a){a!==this.isDarkTheme&&(this.set("isDarkTheme",a),a?(this.leftSquiggly=this.leftSquigglyDark,this.rightSquiggly=this.rightSquigglyDark):(this.leftSquiggly=this.leftSquigglyLight,this.rightSquiggly=this.rightSquigglyLight))};
e.configureRendererStamper=function(){return{"data.actionButton":{id:"action-button",mapping:{buttonRenderer:{component:"ytd-button-renderer",properties:{overrides:"[[actionButtonOverride]]"}}}}}};
g.Object.defineProperties(C8b,{template:{configurable:!0,enumerable:!0,get:function(){if(void 0===B8b){var a=document.createElement("template");J(a,"<!--css-build:shady--><div id=\"left-container\" class=\"style-scope ytd-handles-claiming-header-renderer\">\n  